### PR TITLE
fix(sql): Interpreters should add one join per relation at most

### PR DESCRIPTION
**Pull request by ccatterina**
If a condition specifies the same relation several times the interpreters should add the join statement only once.

Before this patch:
- `typeorm` add a join statement for each condition that refers to the same relation.
- `sequelize` doesn't include any relation because `joins` var was emptied during `merge` operation.

### CODE REVIEW

**Comment by stalniy** [comment]
Thanks for the fix but I think it was fixed in alpha branch, I used `Set<string>` to collect relation names

**Comment by stalniy** [comment]
anyway, thanks for the contribution! I adjusted it for alpha version and going to release a new version now

**Comment by stalniy** [comment]
released in @ucast/sql@1.0.0-alpha.12

**Comment by ccatterina** [comment]
Thanks for merging this!  😃

Next time I will start the PR from the `alpha` branch.

**Pull request merged**
